# Database Configuration for Production (should be set via environment variables in reality)
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}

# Auth0 Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-cuabf3ql66715pfn.us.auth0.com/
app.auth0.audience=https://skillspot-api

# CORS Configuration
app.frontend.origin=https://skillspot.site

# Context Path
server.servlet.context-path=/api
