spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.schemas=skillspot
spring.flyway.default-schema=skillspot
spring.flyway.create-schemas=true
spring.flyway.locations=classpath:db/migration

# Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-cuabf3ql66715pfn.us.auth0.com/
